# Generated by Django 5.0.6 on 2024-08-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('objective', models.TextField()),
                ('features', models.TextField()),
                ('data_representativeness', models.TextField()),
                ('sample_balance', models.BooleanField(blank=True, null=True)),
                ('divided', models.BooleanField(blank=True, null=True)),
                ('missing_values', models.BooleanField(blank=True, null=True)),
                ('temporal_factors', models.BooleanField(blank=True, null=True)),
                ('nb_citations', models.PositiveIntegerField(blank=True, null=True)),
                ('task', models.TextField()),
                ('metadata', models.BooleanField(blank=True, null=True)),
                ('documentation', models.BooleanField(blank=True, null=True)),
                ('learning_indicators', models.TextField()),
                ('informed_consent', models.BooleanField(blank=True, null=True)),
                ('transparency', models.BooleanField(blank=True, null=True)),
                ('user_control', models.BooleanField(blank=True, null=True)),
                ('equity_non_discrimination', models.BooleanField(blank=True, null=True)),
                ('security', models.BooleanField(blank=True, null=True)),
                ('dealing_faulty_data', models.BooleanField(blank=True, null=True)),
                ('anonymization', models.BooleanField(blank=True, null=True)),
                ('keeping_record', models.BooleanField(blank=True, null=True)),
                ('minimal_data_collection', models.BooleanField(blank=True, null=True)),
                ('data_lifecycle_management', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
