# Generated by Django 5.0.6 on 2024-06-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0002_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethicalcriteria',
            name='priority_weight',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='technicalcriteria',
            name='priority_weight',
            field=models.FloatField(default=0.5),
        ),
    ]
