# Generated by Django 5.0.6 on 2024-07-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0003_ethicalcriteria_priority_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ethicalcriteria',
            name='priority_weight',
        ),
        migrations.RemoveField(
            model_name='technicalcriteria',
            name='priority_weight',
        ),
        migrations.AddField(
            model_name='dataset',
            name='ethical_criteria',
            field=models.ManyToManyField(blank=True, to='criteria.ethicalcriteria'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='technical_criteria',
            field=models.ManyToManyField(blank=True, to='criteria.technicalcriteria'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='nb_instances',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='ethicalcriteria',
            name='priority',
            field=models.FloatField(choices=[(0.5, 'Low Priority'), (0.7, 'Medium Priority'), (0.9, 'High Priority')], default=0.5),
        ),
        migrations.AlterField(
            model_name='technicalcriteria',
            name='priority',
            field=models.FloatField(choices=[(0.5, 'Low Priority'), (0.7, 'Medium Priority'), (0.9, 'High Priority')], default=0.5),
        ),
    ]
